### ISSUE TITLE
Module 2 (Structuring data) ready for review

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/rdm-course#13]
This is a DataLad - independent module, dedicated to "good practices", starting with file naming.

I would appreciate comments regarding:

- flow & suitability for inexperienced audience
- time feasibility
- content selection: omissions or unnecessary details
- factual mistakes
- any other details that come to your mind

Course website: https://psychoinformatics-de.github.io/rdm-course/
File content in _episodes folder.

**Comment by adswa** [comment]
I really like the overview of good and bad file names! I wonder if it may be a fun optional exercise to have a list of really bad file names to improve.

### Text versus binary

Good and clear overview, but I would definitely add examples e.g. in form of a table with common file formats. Else, they'll think ``.svg``s are binary and ``.docx`` is a textfile. 

### Version control

maybe rename it to "Implications of file types for version control"?
I think it may be also important, given @mih's preferences from the datalad channel, to somewhat qualify the ``text2git`` configuration. I think it should become clear that this distinction is only relevant for datasets with that configuration and otherwise everything is annexed unless configured otherwise. Maybe also useful to point to the configuration chapters, but I'm not sure if that is not an overload.

### file/directory structure

One item to add could be "The ability of others to understand your project". One thing that could be nice to demonstrate is the importance of keeping inputs and outputs separately that @mih uses in his talks.

```
Original
/dataset
├── sample1
│   └── a001.dat
├── sample2
│   └── a001.dat
...
```

```
After applied transform (preprocessing, analysis, ...)
/dataset
├── sample1
│   ├── ps34t.dat
│   └── a001.dat
├── sample2
│   ├── ps34t.dat
│   └── a001.dat
...
```
-> Without expert/domain knowledge no distinction between original and derived data possible anymore.

versus

```
After applied transform (preprocessing, analysis, ...)
/derived_dataset
├── sample1
│   └── ps34t.dat
├── sample2
│   └── ps34t.dat
├── ...
└── inputs
    └── raw
        ├── sample1
        │   └── a001.dat
        ├── sample2
        │   └── a001.dat
        ...
```
-> Clearer separation of semantics

**Comment by mslw** [comment]
> Maybe also useful to point to the configuration chapters, but I'm not sure if that is not an overload.

That's a good point. I added a link to the handbook because I didn't want to circle around this subject too much (and the reference is definitely valuable for someone who returns to these materials and wants to follow up), but I think the general strategy was to keep the materials fairly straightforward to avoid distracting the first-time reader with too many specifics.

**Comment by mslw** [comment]
I introduced all the suggested changes in the linked PR. 

The "good" and "bad" filenames are all taken from the "Project Structure" presentation linked at the beginning. Fixing "really bad" names does sound like a good idea for an interactive exercise, if I can come up with some nice examples.

Thank you for the comments, feel free to reopen if something else comes along.
